Autogg update
Oondanomala/hFix pull request #1
Opened 2024-03-07 16:53 UTC by yaboistubzz

Autogg update to prevent the same gg message from appearing twice in a row.

2024-03-07 18:13 UTC, yaboistubzz commented
this also includes the option to add custom gg messages.  There are some default messages if the custom ones are not added.

2024-03-09 12:56 UTC, Oondanomala requested changes
Thanks for the changes :D
First review, ill probably change the actual logic myself

2024-03-09 12:56 UTC, Oondanomala commented on src/main/java/me/oondanomala/hfix/config/Config.java
> +        parkourAutoGG = config.getBoolean("Parkour AutoGG", "chat", true, "Automatically says gg whenever someone finishes a parkour. Be careful with this, it can be spam triggered.");
This should remain disabled by default

2024-03-09 12:56 UTC, Oondanomala commented on src/main/java/me/oondanomala/hfix/ChatActions.java
>          // TODO: Handle duplicate messages
You should remove this TODO now

2024-03-09 12:56 UTC, Oondanomala commented on build.gradle
These changes are unnecessary

2024-03-09 12:56 UTC, Oondanomala commented on src/main/java/me/oondanomala/hfix/ChatActions.java
> +}
Add newline to end of file

2024-03-09 12:56 UTC, Oondanomala commented on src/main/java/me/oondanomala/hfix/ChatActions.java
> +    private static int LAST_INDEX = -1;
This shouldn't be static, and since it's not a constant it should be camel case

2024-03-09 12:56 UTC, Oondanomala commented on src/main/java/me/oondanomala/hfix/config/Config.java
> +
Move this (and the code setting the option below) right below `parkourAutoGG`, to be consistent with the other options

2024-03-09 12:56 UTC, Oondanomala commented on src/main/java/me/oondanomala/hfix/config/Config.java
> +        ggList = config.getStringList("Auto GG list", "chat", new String[]{}, "List of gg messages to be displayed upon pk completion. (Minimum 4 messages recommended)");
Just set the default value here (`new String[]{"gg", "gg!"}`), then you can remove the unnecessary logic in `ChatActions`.
I think "gg", "gg!", "GG", "nice" are better defaults. Better to keep it simple IMO

Also, pk -> parkour.

2024-03-12 16:40 UTC, yaboistubzz reviewed
All requested changes should now be resolved.

2024-03-12 17:46 UTC, yaboistubzz reviewed
Mod was broken in the previous push.  Fixed and pushed again.  Mod no longer crashes minecraft.

2024-03-14 14:36 UTC, Oondanomala approved these changes

2024-03-14 14:40 UTC, merged